# -*- coding: utf-8 -*-
"""
Created on Tue Feb 13 16:40:06 2018

@author: Eric
"""
#将原始数据合并完毕，就可以进行数据内容的分类
"""
refference:
    When Social Media Delivers Customer Service: Differential Customer Treatment in the Airline Industry
    we followed a lexicon-based approach to build a classifier to distinguish complaints from all other types of tweets
使用词典的方法：lexicon-based approach to build a classifier to distinguish service-oriented content and sales-oriented content

分析单位：content generated by social media team
for service-oriented content can be:
        1.应用内容
        2.文字内容
for sales-oriented content by social media team
        1.应用内容
        2.文字内容
"""
